### ISSUE TITLE
Add _isA11yCompletionDescriptionEnabled to schema

### ISSUE THREAD

**Issue by oliverfoster** [adaptlearning/adapt-contrib-core#246]
### Subject of the issue
To turn completion status in titles

**Comment by RMurray89** [comment]
This I believe, is in response to my forum post here; https://community.adaptlearning.org/mod/forum/discuss.php?d=4168

Some learners with sight loss find the repetitive nature of the completion status for articles a hindrance rather than a benefit. The ability to have accessibility settings turned on, but without completion status would be ideal. 

An alternative solution (if possible) - with something like the visua11y plugin, would be to give the user control over whether or not these are enabled.

**Comment by oliverfoster** [comment]
Could you perhaps add it to the schemas?

https://github.com/adaptlearning/adapt-contrib-core/blob/master/schema/component.model.schema
https://github.com/adaptlearning/adapt-contrib-core/blob/master/schema/block.model.schema
https://github.com/adaptlearning/adapt-contrib-core/blob/master/schema/article.model.schema
https://github.com/adaptlearning/adapt-contrib-core/blob/master/schema/contentobject.model.schema
https://github.com/adaptlearning/adapt-contrib-core/blob/master/schema/course.model.schema
https://github.com/adaptlearning/adapt-contrib-core/blob/master/schema/content.schema.json

**Comment by RMurray89** [comment]
Possibly but I'm a designer and although I have some technical understanding/ accessibility knowledge I wouldn't know how to do that, unfortunately :)

**Comment by kirsty-hames** [comment]
Looks like [`_disableAccessibleState`](https://github.com/adaptlearning/adapt-contrib-core/issues/186#issuecomment-1193742040) was dropped in favour of `_isA11yCompletionDescriptionEnabled` but the schemas and wiki wasn't updated to reflect this. 

- [Wiki](https://github.com/adaptlearning/adapt_framework/wiki/Core-model-attributes#component-model-attributes) property needs updating.
- `_disableAccessibilityState` needs removing from [header.jsx](https://github.com/adaptlearning/adapt-contrib-core/blob/6be73dead91e631ec5eeb2cacf34f0a33a06837a/templates/header.jsx#L16).
- update schema properties.
