### ISSUE TITLE
Improve breakpoints: Realign existing breakpoints to reflect modern changes in device sizes

### ISSUE THREAD

**Issue by oliverfoster** [adaptlearning/adapt-contrib-core#364]
### Subject of the issue
Ref: https://github.com/adaptlearning/adapt-contrib-core/issues/362

Discussion to try to find the best new set of breakpoints for Adapt. We should keep these as device agnostic as possible as per the existing breakpoints, this is as devices move over time.

It may be wise to start from the areas where we are have troubles styling currently (please list or describe in the comments):
* [Vanilla background images](https://github.com/adaptlearning/adapt-contrib-vanilla/blob/d5a2a5f34f74585fe39723178328d830a76f90e1/example.json#L13-L17)
* [Vanilla responsive classes](https://github.com/adaptlearning/adapt-contrib-vanilla/blob/d5a2a5f34f74585fe39723178328d830a76f90e1/example.json#L23-L27)
* [Box Menu background images](https://github.com/adaptlearning/adapt-contrib-boxMenu/blob/b2c8625fdf6d18674d1bf37de6f598cb8a256a37/example.json#L7-L11)
* [Box Menu header minimum heights](https://github.com/adaptlearning/adapt-contrib-boxMenu/blob/b2c8625fdf6d18674d1bf37de6f598cb8a256a37/example.json#L33-L37)
* [Graphic images sizes](https://github.com/adaptlearning/adapt-contrib-graphic/blob/446c14f4674274c01902999593959bde1d2bcef2/example.json#L15-L16)

### Wild breakpoints
* [Foundation CSS](https://get.foundation/sites/docs/media-queries.html#default-media-queries)
* [Bootstrap](https://getbootstrap.com/docs/5.3/layout/breakpoints/#available-breakpoints)
* [Bulma](https://bulma.io/documentation/overview/responsiveness/#breakpoints)
* [Freecodecamp](https://www.freecodecamp.org/news/css-media-queries-breakpoints-media-types-standard-resolutions-and-more/#common-breakpoints-is-there-a-standard-resolution)
* [Google Material UI](https://m1.material.io/layout/responsive-ui.html#responsive-ui-breakpoints)
* [W3Schools](https://www.w3schools.com/howto/howto_css_media_query_breakpoints.asp)
* [BrowserStack](https://www.browserstack.com/guide/what-are-css-and-media-query-breakpoints#toc6)
* [WebFlow](https://university.webflow.com/lesson/intro-to-breakpoints#toc_heading)
* [Microsoft App Design](https://learn.microsoft.com/en-us/windows/apps/design/layout/screen-sizes-and-breakpoints-for-responsive-design)
* [css-tricks](https://css-tricks.com/snippets/css/media-queries-for-standard-devices/)
* [stackoverflow](https://stackoverflow.com/questions/16443380/common-css-media-queries-break-points)

### Stats
* [screenresolution.org](https://www.screenresolution.org/)
* [W3Schools stats](https://www.w3schools.com/browsers/browsers_display.asp)
* [Google screen resolution stats over time](https://gs.statcounter.com/screen-resolution-stats)

### Devices
* [ios resolutions](https://www.ios-resolution.com/)

### Comments from other issues
* StuartNicholls https://github.com/adaptlearning/adapt-contrib-core/issues/362#issuecomment-1527703361
* kirsty-hames https://github.com/adaptlearning/adapt-contrib-core/issues/362#issuecomment-1525758328
* oliverfoster https://github.com/adaptlearning/adapt-contrib-core/issues/362#issuecomment-1527654454

### Current
| Name | Value | Range | JS | CSS |
|----|----|--------|----|-----|
| n/a | n/a | 0 - 519 | small | small |
| small | 520 | 520 - 759 | small | small |
| medium | 760 | 760 - 899 | medium | medium |
| large | 900 | 900+ | large | large |

**Comment by oliverfoster** [comment]
@StuartNicholls @eleanor-heath @kirsty-hames @guywillis @swashbuck 

Could I have your suggestions for new responsive breakpoints and their numbers please?
I think sensible breakpoints are:

| Name | Value | Range | JS | CSS | Deviceish |
|--------|-------|---------|---|-----|------|
| xsmall | 0 | 0 - 479 | xsmall | xsmall | small mobile |
| small | 480 | 480 - 599 | small | small | mobile |
| medium | 600 | 600 - 959 | medium | medium | small tablet + large mobile |
| large | 960 | 960 - 1279 | large  | large | tablet + desktop |
| xlarge| 1280 | 1280+ | xlarge| xlarge | large tablet + desktop |

**Comment by StuartNicholls** [comment]
@oliverfoster your numbers are very similar to m1 Material breakpoints, they revised these in m2. Actually mine are quite close to m2. m3 the latest has a slightly different approach as its more mobile based I think.. at least at the moment. 
Larger values are better going forward, what with device sizes/laptops/screens increasing etc.

**Comment by StuartNicholls** [comment]
Whats the thinking behind having two 'mobile' breakpoints given we switch to a single col (simple) view currently at the 'medium'  breakpoint. Mobile view should just 'work' in theory, I don't recall ever having to need to refine mobile view at various breakpoints- especially when it comes to images etc. Workflow-wise it seems easier to just make it work at the smallest size when mobile. Mobiles also tend to be lower priority when it comes to actual deliverables also.

**Comment by oliverfoster** [comment]
Sorry mate, was still editing, just thought I'd do something on the fly, it's the first time I've looked at it. It's mostly from the ios screen sizes, testing, the m1 values, our small-medium shift etc. I'll stick a further rationale with my comment after lunch. Could you add a rational to yours please?

**Comment by swashbuck** [comment]
I think I would prefer 1280 as the xlarge breakpoint instead of 1440:
1. 1440 is too big of a jump from 960 (large)
2. In Google’s M1 breakpoints, there’s no real change from 1280 to 1440, at least for columns.
3. Adapt’s default @max-width is 1440. So, using this as a breakpoint may mean it’s never utilized unless this value is increased.
4. Anecdotally, we typically view 1440+ as “widescreen” and don’t worry about it too much. Also, when an LMS admin configures a course to launch in a window, the width is usually constrained to less than 1440 to accommodate the largest number of users.

I do like having a couple smaller breakpoints. For small, though, what about using 400? That would allow us to style smaller phones from newer, larger ones (ex. [iPhone Pro models vs. non-Pro](https://www.ios-resolution.com/))

> Mobiles also tend to be lower priority when it comes to actual deliverables also.

@StuartNicholls I think this is a regional or company-specific trend and shouldn't be considered. Mobile usage can't be dismissed in countries or demographics where users primarily access the internet through mobile devices.

> We do already have xl breakpoint at 1440 for cols functionality

@StuartNicholls Do you have an example of this?

**Comment by oliverfoster** [comment]
@swashbuck 

Vanilla Columns XL:
https://github.com/adaptlearning/adapt-contrib-vanilla/blob/d5a2a5f34f74585fe39723178328d830a76f90e1/less/project/columns.less#L23

**Comment by guywillis** [comment]
> I think I would prefer 1280 as the xlarge breakpoint instead of 1440:
> 
> 1. 1440 is too big of a jump from 960 (large)
> 2. In Google’s M1 breakpoints, there’s no real change from 1280 to 1440, at least for columns.
> 3. Adapt’s default @max-width is 1440. So, using this as a breakpoint may mean it’s never utilized unless this value is increased.
> 4. Anecdotally, we typically view 1440+ as “widescreen” and don’t worry about it too much. Also, when an LMS admin configures a course to launch in a window, the width is usually constrained to less than 1440 to accommodate the largest number of users.

I'm inclined to agree with Brad's points here. 

> I do like having a couple smaller breakpoints. For small, though, what about using 400? That would allow us to style smaller phones from newer, larger ones (ex. [iPhone Pro models vs. non-Pro](https://www.ios-resolution.com/))

For me, I have no real opinion between 360 and 400. Happy with either. 

Potentially, the upside of 360 is the immediate support for background images via the Vanilla theme which would otherwise have to be plumbed in for xsmall if we went with 400?

--
 
> If we had columns XL at 1280 derived from device xlarge at 1280, would it change any behaviour in practice?

I don't believe there would be any negatives from the change. The original implementation attached columns to the `max-page-width` variable as there was nothing else between that and large. With the introduction of a specific device xlarge variable I think this can be changed fairly safely.

**Comment by oliverfoster** [comment]
> Potentially, the upside of 360 is the immediate support for background images via the Vanilla theme which would otherwise have to be plumbed in for xsmall if we went with 400?

If I've understood correctly, this shouldn't be a problem, as `small` and `xsmall` both map to `_small`, meaning it shouldn't matter whether the value is 360 or 400. The vanilla configs are built atop the breakpoints and don't have to map 1:1, think `graphic[small, large]`.

**Comment by guywillis** [comment]
> > Potentially, the upside of 360 is the immediate support for background images via the Vanilla theme which would otherwise have to be plumbed in for xsmall if we went with 400?
> 
> If I've understood correctly, this shouldn't be a problem, as `small` and `xsmall` both map to `_small`, meaning it shouldn't matter whether the value is 360 or 400. The vanilla configs `{_small, _medium, _large}` are built atop the breakpoints and don't have to map 1:1, think `graphic{small, large}`.

Yup, sorry had a mind blank on that aspect. 

-- 

> Name | Value | Range | Distance | Components | Columns | Deviceish
> -- | -- | -- | -- | -- | -- | --
> xsmall | 0 | 0 - 359 | 360 | 1 | 4 | small/old mobile portrait
> small | 360 | 360 - 719 | 360 | 1 | 4 | mobile portrait, small/old mobile landscape
> medium | 720 | 720 - 959 | 240 | 2 | 8 | portait tablet, landscape mobile
> large | 960 | 960 - 1439 | 480 | 2 | 12 | large portrait tablet, landscape tablet, small desktop, laptop, netbook
> xlarge | 1440 | 1440+ | n/a | 2 | 12 | desktop, laptop, etc

Forgot to actually detail above that I am in agreement with these values in principle with Brad's amendments above.

**Comment by StuartNicholls** [comment]
Just to be clear, the thought behind my suggestions are looking forward rather than historical ways of working. So this is where my points are perhaps not coming across. So to me, that’s fundamental, rather than specific breakpoints. I wouldn't be doing my job if I wasn’t suggesting this in my humble opinion.

@swashbuck , I'm not dismissing mobile, actually the opposite of that. So I’m talking about mobile first, a canonical mobile view that  ‘just works’, so in theory 99% of the time it would need little more attention. The canonical view is best practise, our years of experience suggesting the best way to display learning content on small devices. This is where Material is headed, M3, so I do agree Material is a good place to look for ideas, I’m just considering their later thinking but also in a learning context.

So, I differ to M3 thinking in that yes, I’m also suggesting some layouts for tablet/desktop but those are a lighter touch, less defined and are just structural, do addresses some furniture like buttons etc. but more like what we have now, so more of a framework. The theming process becomes additive to the mobile view. So also tries to be a better way of theming the theme. 

So @swashbuck , what I was referring to was purely from an effort / economics point-of-view, demographically we know most people use desktop. So thats where we put the effort in fancying up the theme, spend time adding flourishes there - where there's space to do so. It doesn't mean the mobile view isn't optimised for the content.

I’m not sure why we need two *computed* breakpoints at mobile phone sizes even if we disagree on going a full more like M3, mobile first approach. Obviously, when theming we can add in any additional breakpoints very specific requirements the same way we do now. But in theory, the working practices would mitigate the need for them, design at 320px and it ‘just works’ at sizes up to 600/700 whatever that number is. I'm struggling to see the value of a breakpoint at 360px - are those 40px between 320 (the piratical smallest size) and 360px so vital? The suggestion I’m making captures fidelity at tablet sizes, rather than at mobile phone sizes. 

The reason I went with the 1440+ breakpoint is purely because we already have this ‘soft’ breakpoint, and yes we don’t use it, but do we know others don’t? But anyways.. it’s just a reflection of that. But It does look forward, it only takes tablets to increase in size and we’re there. 

Having said that, I think we’re all in agreement we need a larger breakpoint. We've always needed it for headers and bespoke menus, but going forward it will be required for other projects. Fundamentally, we need to decide whether we need that 1440+ one still, and the value of having a ‘hard’ one at phone sizes or not. This particular point I’m not hard fixed on, I just think from an ethos point of few, looking forward to the next 5 years, the larger one seems better to me. (In addition to the mobile first thing).

As a side, I’d like to establish an adapt base unit, this will help with a harmonious baseline grid, spacing and scaling between breakpoints but also the existing structure (or canonical view(s) ) considering content sizes / gutters and margins. Before we decide on specific point sizes - whether something is 900 or 904 say, shall we decide on the 1440 vs two at mobile sizes / one canonical mobile view first? Would you mind offering some examples of where more ‘hard’ breakpoints are required as small sizes? Especially say, 360 or 400. It’s possible that a better way of working would eliminate the need for this.

**Comment by oliverfoster** [comment]
> Just to clarify what I mean by 'modern css', I'm also proposing we'd do font sizes slightly differently, so rather than have one size at the mobile phone breakpoint. Then optimising that at different breakpoints or for larger phones we'd use a css clamp function. So we'd still set the 'preferred size' in the theme defaults, but we'd also have min and max permissible sizes fixed for that canonical view. Let the css function tied to that canonical view do the work.
> 
> https://developer.mozilla.org/en-US/docs/Web/CSS/clamp

Could you create a separate issue for this please?

**Comment by StuartNicholls** [comment]
@oliverfoster I'm suggesting 1240 so I'm not precious about those few pixels, the only thing I'd say is that lower is closer to a mid point between medium and xLarge and fits nicer with the suggested max content width and margins (and gutters) -calculations-wise. 1200 is good because at the 50% 50% view line lengths would be at the optimal maximum for the default font point-size of 1rem (@16px).

**Comment by oliverfoster** [comment]
@StuartNicholls 

You've gone 704, 904 and 1240 vs my 720, 960 and 1280. Do you have a reference for where these came from? I'm sure I recollect seeing them on my travels, I just can't find the site. Last we spoke you were talking about 768 and not 704?

**Comment by StuartNicholls** [comment]
@oliverfoster , they are inspired by Material M2:

https://m2.material.io/design/layout/responsive-layout-grid.html#breakpoints

But also consider Adapt.

**Comment by oliverfoster** [comment]
@StuartNicholls  Did the 704 value come from device targeting? m2 has 0, 600, 904, 1240, 1440.

**Comment by StuartNicholls** [comment]
@oliverfoster I just wanted to push that closer to the existing mobile/desktop notional breakpoint. Its also getting the limit of a comfortable 50% 50% view. So really I saw that working at xsmall.

**Comment by oliverfoster** [comment]
@StuartNicholls 
So the 704 is an aribitrarily chosen number as the max for single width and the lower bound for the double width transition, which would make the size of a single component, in 2 component layout, 352px? But it hasn't come from an existing breakpoint system with a reference?

**Comment by oliverfoster** [comment]
@swashbuck 

> > I think we could definitely ditch the 360/400 xsmall and just go from 0 - 700/720 for a single column device small.
> 
> @oliverfoster For me, the benefit to having an xsmall breakpoint is for fine-tuning layout issues on mobile devices. For instance, we have the new Navigation Button API. There may be a case where the developer needs to show nav button labels, but they only fit on the screen at 400px and higher. So, we would be able to add an additional small option to the [schemas](https://github.com/adaptlearning/adapt-contrib-core/blob/30bf5b9ab8c71a7623c60dbb199f4561beed6db2/schema/course.schema.json#L646).
> 
> I can't really ever see needing the xsmall breakpoint to configure a background image specific to that size. We typically just use (at most and usually only one) three variants for any given background image.

So 0 - 320/360/400 is really for minor edge-cases but otherwise behaves the same as 320/360/400 - 704/720/760 for most other things?

**Comment by StuartNicholls** [comment]
@oliverfoster , I'm not sure I follow. The 700 comes from the m2 breakpoint of 600 but to work in adapt 50/50 view. So the xsmall one col view would show components at (aprox) 300px wide up to 672 wide (704 - margins).

**Comment by oliverfoster** [comment]
@StuartNicholls
There aren't any devices that start at 704, so you'd be describing only desktop browsers that have been specifically resized to 704. 704 doesn't exist in any of the wider breakpoint layouts on the market. It would give two columns that look like this:

![image](https://github.com/adaptlearning/adapt-contrib-core/assets/7974663/102659bc-4ddd-4ef3-95bf-9f04dbc728e9)

Rather than the 720 / 768, which are referenced in the market, derived from devices, which would give two columns that look like this:
![image](https://github.com/adaptlearning/adapt-contrib-core/assets/7974663/799f57f6-52e5-4e3f-9848-0b8479dc0b40)

Do you have any objection to us using the 700ish value of 720 value, instead of 704?

**Comment by StuartNicholls** [comment]
@oliverfoster not al all, up is good, I was being conservative with the mobile view. As long as its a multiple of 8!

**Comment by StuartNicholls** [comment]
@oliverfoster , I've just remembered why I elected that weird 704. It would make the content width < 700 so content graphics would be produced at 700 wide as opposed to say, 704 but we can fix that with the margin widths in the canonical layout. So yeah 720 or whatever is good.

**Comment by kirsty-hames** [comment]
> @swashbuck
> 
> > > I think we could definitely ditch the 360/400 xsmall and just go from 0 - 700/720 for a single column device small.
> > 
> > 
> > @oliverfoster For me, the benefit to having an xsmall breakpoint is for fine-tuning layout issues on mobile devices. For instance, we have the new Navigation Button API. There may be a case where the developer needs to show nav button labels, but they only fit on the screen at 400px and higher. So, we would be able to add an additional small option to the [schemas](https://github.com/adaptlearning/adapt-contrib-core/blob/30bf5b9ab8c71a7623c60dbb199f4561beed6db2/schema/course.schema.json#L646).
> > I can't really ever see needing the xsmall breakpoint to configure a background image specific to that size. We typically just use (at most and usually only one) three variants for any given background image.
> 
> So 0 - 320/360/400 is really for minor edge-cases but otherwise behaves the same as 320/360/400 - 704/720/760 for most other things?

I find the layout edge cases (as per @swashbuck's example) are usually very AD/theme/functionality specific (e.g how many nav plugins are used in a course and the styling of the labels) that I always use random screen width values (at the point the layout breaks) rather than a defined breakpoint. Even with an additional xsmall breakpoint I think the value required will always be specific to each layout issue if that makes sense.

**Comment by oliverfoster** [comment]
I think we have some consensus forming around the values

### Proposed values
All breakpoints are multiples of 8.

| Name | Value | Range | Distance | Components | Columns | Deviceish |
|--------|-------|---------|--|-----|----|----|
| small | 0 | 0- 719 | 720 | 1 | 4 | mobile portrait |
| medium | 720 | 720 - 959 | 240 | 2 | 8 | portait tablet, landscape mobile |
| large | 960 | 960 -  1279 | 480 | 2 | 12 | large portrait tablet, landscape tablet, small desktop, laptop, netbook |
| xlarge | 1280 | 1280+ | n/a | 2 | 12 | desktop, laptop, etc |

* `small` is for single component views
* `medium` and above are for double component views
* `xlarge` is at 1280 to match up with [Google M1 breakpoints](https://m1.material.io/layout/responsive-ui.html#responsive-ui-breakpoints)
* `@max-width` at 1440, for limiting the maximum container widths
* Edge cases for ultra small devices can be specifically created in a theme

**Comment by oliverfoster** [comment]
> @oliverfoster , I've just remembered why I elected that weird 704. It would make the content width < 700 so content graphics would be produced at 700 wide as opposed to say, 704 but we can fix that with the margin widths in the canonical layout. So yeah 720 or whatever is good.

I'm really struggling to get a definition for canonical layouts and how it ties in with Adapt. In M3 it just means that they have 3 standard layouts which can be maped to all of the device breakpoints behind the scenes, such that developers don't have to worry about it.

The actual definition of Canonical in computer science is:
> Canonical, in computer science, is the standard state or behaviour of an attribute. There are two building blocks of a canonical device, its interface, and its internal structure.

We have 2 standard layouts: 
1. single component 
2. double component 

We have 4 standard breakpoints:
1. small
2. medium
3. large
4. xlarge

We have 3 standard devices:
1. mobile
2. tablet
3. desktop


By realigning the two standard layouts to the small-medium boundary, we effectively have:
1. single component = small = mobile
2. double component = medium / large = tablet portrait, tablet landscape
3. double component = large / xlarge = desktop

What is your understanding of the meaning of the term canonical?

**Comment by StuartNicholls** [comment]
@oliverfoster I think minimising the extra breakpoints is a very good idea, especially for AAT complexities. Four I'm more comfortable with in that regard. So moving that larger one as you've suggested is probably best, but will confirm just in case I've forgotten something.

**Comment by swashbuck** [comment]
> I think we have some consensus forming around the values

@oliverfoster Yep, these 4 sound good to me.

**Comment by oliverfoster** [comment]
Previous:
![image](https://github.com/adaptlearning/adapt-contrib-core/assets/7974663/d4657a4c-4359-4195-86c7-1d21909005b9)

Proposed:
![image](https://github.com/adaptlearning/adapt-contrib-core/assets/7974663/90c998c8-cadb-4a17-96a1-7cb32f222f65)

**Comment by swashbuck** [comment]
@oliverfoster Is there a reason we're reducing the @max-page-width value to 1280? I would think it stays at 1440.

**Comment by oliverfoster** [comment]
Fixed in https://github.com/adaptlearning/adapt-contrib-core/pull/372
