### ISSUE TITLE
replace hamburger icon in navbar

### ISSUE THREAD

**Issue by chucklorenz** [adaptlearning/adapt-contrib-core#417]
The hamburger icon in the navbar opens the Drawer. Ought we consider replacing this icon with a sidebar icon?
![sidebar-icon](https://github.com/adaptlearning/adapt-contrib-core/assets/9489014/2403f41b-068c-411b-a638-ec84959309a6)

Rationale:
- The hamburger icon visually represents a vertical list and, in my experience, is overwhelmingly associated with menus.  Consider that the icon used to indicate a list frequently includes "bullets" to distinguish its meaning from the hamburger menu icon. While the Drawer frequently contains lists like Resources and Glossary, the only time it contains a menu is when something like Kineo's TOC is deployed.
- Icons have evolved, and the sidebar icon is finding more use, especially when changing layouts. 
- "Drawer" is a technical label that doesn't get much use anymore. It's more likely to see the term "sidebar" due to its print analog or "sheet". All these terms broadly denote a containing structure. A menu icon feels too narrow for a structure that rarely ever contains an actual menu. If there were an icon that was recognized to mean "resources" or "supplements" or "accessories", that might be a bit more enticing than a sidebar icon. But a menu icon actually feels misleading.

@StuartNicholls @guywillis @kirsty-hames

**Comment by kirsty-hames** [comment]
Makes sense to me @chucklorenz. I think your suggestion of a sidebar icon is a better representation of the existing functionality/display.

Seeing as Drawer can be utilised for many plugins/functionalities, it would be ideal if you could configure the icon per course to make it relevant to the plugins/functionality being used (instead of having to override the icon class via CSS).
