### ISSUE TITLE
`calculateLevel` issue when returning to a completed course

### ISSUE THREAD

**Issue by danielghost** [adaptlearning/adapt-contrib-core#453]
If a completed course is relaunched, the following error occurs when the menu is rendered, and will prevent page loading from the menu:
```JavaScript
adapt.js:141 Uncaught TypeError: Cannot read properties of undefined (reading 'replace')
    at AdaptSingleton.parseRelativeString (adapt.js:141:8)
    at calculateLevel (a11y.js:217:40)
    at calculateLevel (a11y.js:236:14)
    at A11y.ariaLevel (a11y.js:238:12)
    at Object.a11y_aria_level (helpers.js:345:32)
    at Object.c (handlebars.min.js:27:19853)
    at Object.main (templates.js:389:120)
    at c (handlebars.min.js:27:15429)
    at d (handlebars.min.js:27:15744)
    at Object.<anonymous> (templates.js:26:17)
```
Only seems to occur for courses with a role selector, but is due to the completion checking which such plugins perform after modifying the availibility of models when the course loads. When the completion changes, [`updateAria()`](https://github.com/adaptlearning/adapt-contrib-core/blob/master/js/views/headingView.js#L23C1-L29) gets called but errors due to no `_ariaLevel` being defined for the 'course' `_type` - https://github.com/adaptlearning/adapt_framework/blob/master/src/course/config.json#L14-L24.

Why do we convert 'course' to 'menu' in https://github.com/adaptlearning/adapt-contrib-core/blob/master/js/views/headingView.js#L18 rather than just adding `"_course": 1` in _config.json_?

May be related to https://github.com/adaptlearning/adapt-contrib-core/issues/355.

**Comment by oliverfoster** [comment]
We shouldn't really have page and menu on the ariaLevels, we should just have contentobject, as this is the main content unit and their aria level will always start from 1, we never need to change that config unless something big change. course gets converted to menu because it is a menu and uses the menu value. course is just the main menu, still 1.

**Comment by oliverfoster** [comment]
There is not enough information here to reproduce the issue. Could you find out which component is rendering its template and when it is doing it please?

**Comment by swashbuck** [comment]
We have had a client report this issue. The course uses Role Selector. I can reproduce it in SCORM Cloud but not locally when using _scorm_test_harness.html_.

Would either of these solutions resolve the issue?

1. Set a default value for `level` in [calculateLevel()](https://github.com/adaptlearning/adapt-contrib-core/blob/8b36e3ee68941b62e711198f49fa9345c1758132/js/a11y.js#L209):

```
function calculateLevel(id = null, level = 1, offset = 0) {
```

2. Add `"course": 1` to `_accessibility._ariaLevels` in [course.json](https://github.com/adaptlearning/adapt_framework/blob/11d5f1e9d10473df9a7b90dcfe5a079cab7c202d/src/course/config.json#L14)

In `calculateLevel()`, I'm outputting the `id` and `level` to the console.

```
console.log(`ariaLevel level for ${id} is ${level}`);
```

Note that it checks for `course` twice, and the first time `level` is not undefined. Presumably, this is due to the function trying to traverse the parents of `course` and then not finding any.

```
ariaLevel level for course is course adapt.min.js:1:54995
ariaLevel level for course is undefined adapt.min.js:1:54995
Uncaught TypeError: relativeString is undefined
    parseRelativeString https://adapt/js/adapt.min.js:1
    calculateLevel https://adapt/js/adapt.min.js:1
    calculateLevel https://adapt/js/adapt.min.js:1
    ariaLevel https://adapt/js/adapt.min.js:1
    a11y_aria_level https://adapt/js/adapt.min.js:1
    c https://libraries/handlebars.min.js:27
    main https://templates.js:1
    c https://libraries/handlebars.min.js:27
    d https://libraries/handlebars.min.js:27
    <anonymous> https://adapt/js/adapt.min.js:1
    updateAria https://adapt/js/adapt.min.js:1
    Backbone 5
    set https://adapt/js/adapt.min.js:1
    checkCompletionStatusFor https://adapt/js/adapt.min.js:1
    ir Underscore
adapt.min.js:1:7167
ariaLevel level for co-100 is menuItem adapt.min.js:1:54995
ariaLevel level for co-200 is menuItem adapt.min.js:1:54995
ariaLevel level for co-300 is menuItem adapt.min.js:1:54995
```

**Comment by oliverfoster** [comment]
Please repost the call stack with sourcemaps enabled.

**Comment by swashbuck** [comment]
@oliverfoster Updated my comment above with sourcemaps enabled.

**Comment by oliverfoster** [comment]
I don't understand how `level` is `course`, from a handlebars context.

This is where it is changed:
https://github.com/adaptlearning/adapt-contrib-core/blob/8b36e3ee68941b62e711198f49fa9345c1758132/js/views/headingView.js#L18-L19

It's almost as if the heading is rendered directly and not through [heading.hbs](https://github.com/adaptlearning/adapt-contrib-core/blob/master/templates/heading.hbs) as in [boxMenu](https://github.com/adaptlearning/adapt-contrib-boxMenu/blob/8b481c78c4598f0adc633fd7bf28306e97dea815/templates/boxMenu.hbs#L19). Which menu is being used?

**Comment by oliverfoster** [comment]
Please try the above pr.

Unanswered questions:
* Which menu
* Where is level "course" coming from

**Comment by swashbuck** [comment]
@oliverfoster It looks like `level` _is_ "menu" after I complete the course initially. However, upon revisit, `level` uses "course." So, it apparently doesn't get converted when revisiting.
